name: Testes de Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Instalar Maven (opcional, se necessário)
        run: sudo apt-get install -y maven

      - name: Construir e rodar testes
        run: mvn clean verify

      - name: Rodar testes específicos
        run: |
            mvn -Dtest=br.org.unicortes.barbearia.services.BarberServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.ClientServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.LoyaltyCardServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.ProductServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.PromocaoServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.SaleServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.ServicoServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.StockServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.ServiceAppointmentServiceTest test 
            mvn -Dtest=br.org.unicortes.barbearia.services.AvailableTimeServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.services.AuthServiceTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.BarberIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.ClientIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.LoyaltyCardIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.ProductIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.PromocaoIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.SaleIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.ServicoIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.StockIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.ServiceAppointmentIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.AvailableTimeIntegrationTest test
            mvn -Dtest=br.org.unicortes.barbearia.controllers.AuthIntegrationTest test

      - name: Exibir versão do Maven (opcional, para depuração)
        run: mvn -version
